#!/bin/bash

PS2TOOLCHAIN_DVP_BINUTILS_REPO_URL="https://github.com/ps2dev/binutils-gdb.git"
PS2TOOLCHAIN_DVP_BINUTILS_DEFAULT_REPO_REF="dvp-v2.45.1"

PS2TOOLCHAIN_DVP_MASP_REPO_URL="https://github.com/ps2dev/masp.git"
PS2TOOLCHAIN_DVP_MASP_DEFAULT_REPO_REF="v0.1.16"

PS2TOOLCHAIN_DVP_OPENVCL_REPO_URL="https://github.com/ps2dev/openvcl.git"
PS2TOOLCHAIN_DVP_OPENVCL_DEFAULT_REPO_REF="v0.4.0"

if test -f "$PS2DEV_CONFIG_OVERRIDE"; then
  source "$PS2DEV_CONFIG_OVERRIDE"
fi
