name: CI-Docker

on:
  push:
    branches:
      - master
      - main
    tags:
      - v*
    paths-ignore:
      - '**.md'
      - '**.rst'
  workflow_dispatch: {}
  repository_dispatch:
    types:
      - run_build

jobs:
  build:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    outputs:
      dest-repo: ${{ steps.dest-repo.outputs.DEST_REPO }}
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 180

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract DOCKER_TAG using tag name
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        printf 'DOCKER_TAG=%s\n' "${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    
    - name: Use default DOCKER_TAG
      if: startsWith(github.ref, 'refs/tags/') != true
      run: |
        printf 'DOCKER_TAG=%s\n' "latest" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v3
      if: env.DOCKER_USERNAME != null
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set docker tag list to include DockerHub if credentials available
      if: env.DOCKER_USERNAME != null
      run: |
        printf 'DOCKER_TAG_LIST=%s\n' "ghcr.io/${{ github.repository }}:${{ env.DOCKER_TAG }},${{ github.repository }}:${{ env.DOCKER_TAG }}" >> $GITHUB_ENV

    - name: Set docker tag list to not include DockerHub if credentials not available
      if: env.DOCKER_USERNAME == null
      run: |
        printf 'DOCKER_TAG_LIST=%s\n' "ghcr.io/${{ github.repository }}:${{ env.DOCKER_TAG }}" >> $GITHUB_ENV

    - name: Prepare additional environment variables from repo
      run: if test -f ./config/ci-docker-env.ini; then cat ./config/ci-docker-env.ini | sed -e 's/$REPOSITORY_OWNER/'"${{ github.repository_owner }}"'/g;s/$DOCKER_TAG/'"${{ env.DOCKER_TAG }}"'/g' >> $GITHUB_ENV; fi

    - name: Build and Push to container registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.DOCKER_TAG_LIST }}
        build-args: |
          BASE_DOCKER_IMAGE
          BASE_DOCKER_DVP_IMAGE
          BASE_DOCKER_IOP_IMAGE
          BASE_DOCKER_EE_IMAGE

    - name: Gather information for repository dispatch
      id: dest-repo
      run: if test -f ./config/repository-dispatch.ini; then cat ./config/repository-dispatch.ini >> $GITHUB_OUTPUT; fi

  perform-repository-dispatch:
    needs:
      - build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      options: "--user 0"
    timeout-minutes: 20
    env:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
    strategy:
      matrix:
        dest-repo: ${{ fromJson(needs.build.outputs.dest-repo) }}

    steps:
    - name: Gather environment variables (normal)
      if: github.event_name != 'repository_dispatch'
      run: |
        printf 'PAYLOAD_REPO_PARENT_NAME=%s\n' "${{ github.repository }}" >> $GITHUB_ENV
        printf 'PAYLOAD_REPO_PARENT_SHA=%s\n' "${{ github.sha }}" >> $GITHUB_ENV

    - name: Gather environment variables (dispatch)
      if: github.event_name == 'repository_dispatch'
      run: |
        printf 'PAYLOAD_REPO_PARENT_NAME=%s\n' "${{ github.event.client_payload.parent_name }}" >> $GITHUB_ENV
        printf 'PAYLOAD_REPO_PARENT_SHA=%s\n' "${{ github.event.client_payload.parent_sha }}" >> $GITHUB_ENV

    - name: Send Compile action
      run: |
        export DISPATCH_ACTION="$(printf 'run_build\n')"
        printf 'NEW_DISPATCH_ACTION=%s\n' "$DISPATCH_ACTION" >> $GITHUB_ENV

    - name: Repository Dispatch to ${{ matrix.dest-repo }}
      uses: peter-evans/repository-dispatch@v3
      if: env.DISPATCH_TOKEN != null && !contains(matrix.dest-repo, '/')
      with:
        repository: ${{ github.repository_owner }}/${{ matrix.dest-repo }}
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: ${{ env.NEW_DISPATCH_ACTION }}
        client-payload: '{"ref": "${{ github.ref }}", "parent_name": "${{ env.PAYLOAD_REPO_PARENT_NAME }}", "parent_sha": "${{ env.PAYLOAD_REPO_PARENT_SHA }}"}'

    - name: Repository Dispatch to specific ${{ matrix.dest-repo }}
      uses: peter-evans/repository-dispatch@v3
      if: env.DISPATCH_TOKEN != null && contains(matrix.dest-repo, '/')
      with:
        repository: ${{ matrix.dest-repo }}
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: ${{ env.NEW_DISPATCH_ACTION }}
        client-payload: '{"ref": "${{ github.ref }}", "parent_name": "${{ env.PAYLOAD_REPO_PARENT_NAME }}", "parent_sha": "${{ env.PAYLOAD_REPO_PARENT_SHA }}"}'
